version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  enqueue-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    volumes:
      - ./enqueue:/usr/src/app/enqueue

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./worker:/usr/src/app/worker
      - ./enqueue:/usr/src/app/enqueue
